# Generated by Django 2.2.4 on 2019-08-25 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfig',
        ),
    ]
